// Cars and trucks only (Jonah, 2026-10-09): gov-surplus and auction adapters keep passenger cars,
// pickups, SUVs, vans and light/medium trucks. Everything else that carries a model year in surplus
// catalogs (aircraft, boats, trailers, tractors, forklifts, heavy machinery, buses, motorcycles,
// powersports, equipment) is dropped before it reaches the deals table.

const NOT_CAR_OR_TRUCK = new RegExp(
  [
    // aircraft & watercraft
    "aircraft",
    "airplane",
    "helicopter",
    "cessna",
    "piper",
    "beechcraft",
    "blackhawk",
    "drone",
    "boat",
    "vessel",
    "whaler",
    "pontoon",
    "jet ?ski",
    "watercraft",
    "outboard",
    "kayak",
    "canoe",
    // trailers & towables
    "trailer",
    "camper",
    "fifth wheel",
    "travel trailer",
    "toy hauler",
    // ag / construction / industrial
    "tractor",
    "loader",
    "backhoe",
    "excavator",
    "dozer",
    "bulldozer",
    "skid ?steer",
    "forklift",
    "fork lift",
    "crane",
    "grader",
    "paver",
    "roller",
    "compactor",
    "trencher",
    "telehandler",
    "scissor lift",
    "boom lift",
    "man ?lift",
    "manlift",
    "aerial lift",
    "mower",
    "combine",
    "harvester",
    "baler",
    "sprayer",
    "generator",
    "compressor",
    "welder",
    "pump",
    "sweeper",
    "street sweeper",
    "john deere",
    "kubota",
    "bobcat",
    "caterpillar",
    "\\bcat \\d",
    "case ih",
    "new holland",
    // heavy trucks / buses
    "semi",
    "truck tractor",
    "sleeper",
    "dump truck",
    "garbage",
    "refuse",
    "fire truck",
    "fire apparatus",
    "pumper",
    "ladder truck",
    "bus",
    "school bus",
    "motor ?coach",
    "motorhome",
    "rv\\b",
    "cascadia",
    "peterbilt",
    "kenworth",
    "mack\\b",
    "western star",
    "class 8",
    // powersports / small
    "motorcycle",
    "harley",
    "scooter",
    "moped",
    "atv",
    "utv",
    "side ?by ?side",
    "polaris",
    "can-am",
    "gator",
    "mule",
    "golf cart",
    "snowmobile",
    "go ?kart",
    "dirt bike",
    // non-vehicles that slip in with a year
    "counter",
    "machine",
    "cabinet",
    "furniture",
    "equipment",
    "engine only",
    "parts lot",
  ]
    .map((w) => (w.startsWith("\\b") || w.endsWith("\\b") ? w : `\\b${w}\\b`))
    .join("|"),
  "i",
);

/** True for passenger cars, pickups, SUVs, vans and light/medium trucks. */
export function isCarOrTruck(title: string | null | undefined): boolean {
  const t = String(title || "")
    .replace(/\s+/g, " ")
    .trim();
  if (!t) return false;
  return !NOT_CAR_OR_TRUCK.test(t);
}
