/**
 * Where to point location-based sites when we only know a ZIP. Craigslist and Facebook need a
 * city/site slug in the URL; we pick the state's biggest market and let the ZIP + radius params
 * (where the site supports them) do the real centering.
 */
export const CRAIGSLIST_SITE_BY_STATE: Record<string, string> = {
  AL: "birmingham",
  AK: "anchorage",
  AZ: "phoenix",
  AR: "littlerock",
  CA: "losangeles",
  CO: "denver",
  CT: "hartford",
  DC: "washingtondc",
  DE: "delaware",
  FL: "miami",
  GA: "atlanta",
  HI: "honolulu",
  IA: "desmoines",
  ID: "boise",
  IL: "chicago",
  IN: "indianapolis",
  KS: "wichita",
  KY: "louisville",
  LA: "neworleans",
  MA: "boston",
  MD: "baltimore",
  ME: "maine",
  MI: "detroit",
  MN: "minneapolis",
  MO: "stlouis",
  MS: "jackson",
  MT: "montana",
  NC: "charlotte",
  ND: "fargo",
  NE: "omaha",
  NH: "nh",
  NJ: "newjersey",
  NM: "albuquerque",
  NV: "lasvegas",
  NY: "newyork",
  OH: "columbus",
  OK: "oklahomacity",
  OR: "portland",
  PA: "philadelphia",
  RI: "providence",
  SC: "columbia",
  SD: "siouxfalls",
  TN: "nashville",
  TX: "dallas",
  UT: "saltlakecity",
  VA: "norfolk",
  VT: "vermont",
  WA: "seattle",
  WI: "milwaukee",
  WV: "wv",
  WY: "wyoming",
};

/** Facebook Marketplace city slugs we are confident about. Other states use the location-free search. */
export const FACEBOOK_CITY_BY_STATE: Record<string, string> = {
  AZ: "phoenix",
  CA: "la",
  CO: "denver",
  FL: "miami",
  GA: "atlanta",
  IL: "chicago",
  MA: "boston",
  MI: "detroit",
  MN: "minneapolis",
  MO: "stlouis",
  NC: "charlotte",
  NV: "lasvegas",
  NY: "nyc",
  OR: "portland",
  PA: "philly",
  TN: "nashville",
  TX: "dallas",
  WA: "seattle",
};
