// A verification checklist, not a legal eligibility or registration decision.
export const DEFAULT_REQUIREMENTS = [
  "Confirm title brand and registration eligibility for this vehicle",
  "Confirm required title, bill of sale, odometer and lien-release documents",
  "Confirm inspection and emissions requirements for the destination county and vehicle type",
  "Confirm insurance, taxes, fees and registration deadlines",
  "Confirm any transit permit needed before driving across state lines",
];

export function getTitleRules(_fromState: string, _toState: string) {
  return {
    warning: true,
    note: "Registration requirements depend on the vehicle, title brand, buyer and destination jurisdiction. This checklist does not establish eligibility. Verify with the destination motor vehicle agency before purchase or transport.",
    requirements: DEFAULT_REQUIREMENTS,
    agencyUrl: "https://www.usa.gov/state-motor-vehicle-services",
  };
}

export const US_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];
