// The ONLY deals columns the anon / authenticated Postgres roles may SELECT directly over
// PostgREST / Realtime (see supabase/migrations/20261010020000_deals_column_grants.sql).
// Everything else — flip economics, raw embedding, exact geo, seller contact in `options`,
// internal ids and dedupe/cache flags — is server-only (service role) and reaches the browser
// only through an API route that applies the desk gate.
// Keep this list and the migration's list identical (deals-column-privileges.test.ts checks).
export const DEALS_PUBLIC_COLUMNS = [
  "id",
  "source",
  "source_url",
  "title",
  "year",
  "make",
  "model",
  "trim",
  "vin",
  "mileage",
  "condition",
  "damage_type",
  "body_class",
  "body_style",
  "drivetrain",
  "engine",
  "fuel_type",
  "transmission",
  "color",
  "assembly_country",
  "assembly_plant",
  "recalls_count",
  "keys_present",
  "run_drive",
  "ask_price",
  "buy_now_price",
  "price_drop_amount",
  "price_drop_days",
  "last_price_change_at",
  "images",
  "location_city",
  "location_state",
  "active",
  "availability_status",
  "auction_end_at",
  "first_seen_at",
  "last_seen_at",
  "created_at",
  "updated_at",
] as const;

/** Never grantable to anon / authenticated, whatever the list above says. */
export const DEALS_SERVER_ONLY_COLUMNS = [
  "embedding",
  "embedded_at",
  "embedding_source_hash",
  "lat",
  "lng",
  "location",
  "location_zip",
  "pricing_breakdown",
  "options",
  "dealer_id",
  "source_deal_id",
  "duplicate_of_id",
  "duplicate_confidence",
  "flash_alert_sent",
  "images_cached",
  "kbb_trade_in",
  "kbb_retail",
  "cargurus_price",
  "mmr_value",
  "estimated_transport_cost",
  "estimated_repair_cost",
  "profit_estimate",
  "profit_score",
  "true_net_profit",
  "recommended_max_bid",
  "deal_verdict",
  "deal_analysis",
  "ai_wholesale_estimate",
  "ai_retail_estimate",
  "ai_rationale",
  "is_arbitrage_opportunity",
  "price_gap_detected",
  "sell_estimate",
] as const;
